### ISSUE TITLE
Create application frontend

### ISSUE THREAD

**Issue by gmacario** [aquariophilie/blobfishes#10]
Completion criteria: At least one page for

- [ ] **C**reate
- [x] **R**ead
- [ ] **U**pdate
- [ ] **D**elete

as required by the [Digital Ocean MongoDB Hackathon](https://www.digitalocean.com/mongodb-hackathon/) rules.

**Comment by gmacario** [comment]
@alv67 I merged #78 and #80 - can this task be considered complete now?

**Comment by alv67** [comment]
Yes. 

More work can be done, this is opportunity for other tasks...
